# Generated by Django 5.2.7 on 2025-10-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL amigável (ex: intro-ao-python)', unique=True)),
                ('ordem', models.IntegerField(help_text='Ordem em que a lição aparecerá', unique=True)),
                ('tipo', models.CharField(choices=[('video', 'Vídeo de Conteúdo'), ('codigo', 'Desafio de Código')], max_length=10)),
                ('url_video', models.URLField(blank=True, help_text="URL do Embed do YouTube (apenas se for 'Vídeo de Conteúdo')", null=True)),
                ('conselho', models.TextField(help_text='Descrição do desafio/instrução')),
                ('esperado', models.TextField(blank=True, help_text="Saída exata esperada no console (apenas se for 'Desafio de Código')", null=True)),
                ('codigo_padrao', models.TextField(blank=True, help_text="Código inicial no editor (apenas se for 'Desafio de Código')", null=True)),
            ],
            options={
                'verbose_name_plural': 'Lições',
                'ordering': ['ordem'],
            },
        ),
    ]
