# Generated by Django 5.2.7 on 2025-10-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licao',
            name='conselho',
            field=models.TextField(help_text='Descrição do desafio/instrução ou dica'),
        ),
    ]
