# Generated by Django 5.2.7 on 2025-10-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_licao_conselho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licao',
            name='conselho',
            field=models.TextField(help_text='Descrição do desafio/instrução'),
        ),
    ]
